language: node_js
node_js:
  - "0.10"
install:
  - npm install phantomjs -g
  - npm install -g mocha-phantomjs
  - npm install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
script:
  - make test
  - mocha-phantomjs testRunner.html