language: node_js
node_js:
  - "0.10"
install:
  - npm install phantomjs -g
  - npm install -g mocha-phantomjs
  - gem install sass
  - npm install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
script:
  - npm run build-files
  - npm run test